# [3.27.0] - 2023-4-27

更新: @zenweb/result: 3.7.1 外部 fail() 方法，去除 ctx.result，获取 success 数据请使用 ctx.successData 属性 

```ts
import { mapping, fail, Context } from 'zenweb';

export class DemoController {
  @mapping()
  demo(ctx: Context) {
    // 之前需要注入 Context 对象才能调用 fail 方法
    ctx.fail('some-error');

    // 更新后直接使用 fail 方法
    fail('some-error');
  }
}
```
